//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POSTestingEntities : DbContext
    {
        public POSTestingEntities()
            : base("name=POSTestingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<SP_GET_USERS_ALL_Result> SP_GET_USERS_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_USERS_ALL_Result>("SP_GET_USERS_ALL");
        }
    
        public virtual ObjectResult<SP_GET_USER_DELETED_Result> SP_GET_USER_DELETED()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_USER_DELETED_Result>("SP_GET_USER_DELETED");
        }
    }
}
