//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string PassWord { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Avatar { get; set; }
    
        public bool Remember { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Role Role { get; set; }
    }
}
